name: globe
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs
  - geopandas
  - humanize
  - fastparquet
  - datashader
  - dask
  - s3fs
  - pandas
  - shapely
  - geoplot
  - matplotlib
  - numpy
  - cartopy
  - jupyter
